export { default as Dashboard } from './Dashboard/dashboard';
export { default as History } from './History/history';
export { default as Workout } from './Workout/workout';
export { default as Exercises } from './Exercises/exercises';
export { default as Login } from './Login/login';
export { default as SignUp } from './SignUp/signup';
export { default as LogWorkout } from './LogWorkout/logworkout';
export { default as ErrorPage } from './ErrorPages/errorPage';
export { default as Landing } from './Landing/landing';