export { default as Dashboard } from './Dashboard'
export { default as Landing } from './Landing'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as AddWorkout } from './AddWorkout/addworkout'
export { default as SubmitWorkout } from './SubmitWorkout/submitworkout'
export { default as Workout } from './Workout/workout'
export { default as History } from './History/history'
export { default as LogWorkout } from './LogWorkout/logworkout'
export { default as ErrorPage } from './ErrorPages/errorPage'
export { default as Friends} from './Friends/index'
export { default as FriendsForm} from './FriendsForm/index'
export { default as Stats} from './Stats/index'
