export { default as Dashboard } from './Dashboard'
export { default as Landing } from './Landing'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as AddWorkout } from './AddWorkout/addworkout'
export { default as SubmitWorkout } from './SubmitWorkout/submitworkout'
export { default as Workout } from './Workout/workout'
